name: Deploy
on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: LLK/scratch-gui
          ref: develop
      - run: npm install
      - uses: actions/checkout@v2
        with:
          path: ./scratch3
      - uses: actions/checkout@v2
        with:
          repository: champierre/ml2scratch
          path: ./ml2scratch
      - uses: actions/checkout@v2
        with:
          repository: champierre/posenet2scratch
          path: ./posenet2scratch
      - uses: actions/checkout@v2
        with:
          repository: yokobond/scratch-vm
          ref: extension/microbit-more
          path: ./microbit-more-scratch-vm
      - uses: actions/checkout@v2
        with:
          repository: yokobond/scratch-ext
          ref: microbit-more
          path: ./microbit-more-scratch-ext
      - uses: actions/checkout@v2
        with:
          repository: champierre/tm2scratch
          path: ./tm2scratch
      - uses: actions/checkout@v2
        with:
          repository: champierre/scratch2maqueen
          path: ./scratch2maqueen
      - uses: actions/checkout@v2
        with:
          repository: champierre/handpose2scratch
          path: ./handpose2scratch
      - uses: actions/checkout@v2
        with:
          repository: champierre/facemesh2scratch
          path: ./facemesh2scratch
      - uses: actions/checkout@v2
        with:
          repository: con3office/pasorich
          path: ./pasorich
      - uses: actions/checkout@v2
        with:
          repository: champierre/speech2scratch
          path: ./speech2scratch
      - uses: actions/checkout@v2
        with:
          repository: champierre/ic2scratch
          path: ./ic2scratch
      - run: sh ./ic2scratch/install.sh
      - run: sh ./speech2scratch/install.sh
      - run: sh ./scratch3/pasorich/install.sh
      - run: sh ./handpose2scratch/install.sh
      - run: sh ./facemesh2scratch/install.sh
      - run: sh ./scratch2maqueen/install.sh
      - run: sh ./tm2scratch/install.sh
      - run: sh ./tm2scratch/install_microbit_more.sh
      - run: sh ./posenet2scratch/install.sh
      - run: sh ./ml2scratch/install.sh
      - run: sh ./scratch3/add_ga_tracking_code.sh
      - run: cat node_modules/scratch-vm/src/extension-support/extension-manager.js
      - run: npm run build
      - run: cp ./scratch3/index.html ./build/index.html
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
